require('dotenv').config({ path: __dirname +'/.env', debug: true });
var config = {};
config.listenPort = process.env.timelapsePort;
config.setLapseSeconds = process.env.setLapseSeconds;
config.imageSaveDir = "images/";
config.videoSaveDir = "videos/";
config.httpOrHttps = "http";
config.timeLapseDir = "time-lapse-vids";
config.timeLapseURL = process.env.timelapseURL;
module.exports = config;